Nemesys/Controllers/HallOfFameController.cs
using Microsoft.AspNetCore.Mvc;
using Nemesys.Repositories.Interfaces;

namespace Nemesys.Controllers
{
    public class HallOfFameController : Controller
    {

        private readonly IReportRepository reportrepo;

        public HallOfFameController(IReportRepository reportrepo)
        {
            this.reportrepo = reportrepo;
        }

        public IActionResult Index()
        {
            var CurrentYear = DateTime.Now.Year;
            var Results = reportrepo.GetReporterRankings(CurrentYear);
            return View(Results);
        }
    }
}

Nemesys/Controllers/ReportPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Nemesys.Data;
using Nemesys.Models;
using Nemesys.Models.ViewModels;
using Nemesys.Repositories;
using Nemesys.Repositories.Interfaces;

namespace Nemesys.Controllers
{
    public class ReportPostsController : Controller
    {
        private IReportRepository _reportRepository { get; set; }
        public string ImageUrl { get; private set; }

        private readonly NemesysContext _context;
        private readonly UserManager<AppUser> _userManager;

        public ReportPostsController(NemesysContext context, IReportRepository reportRepository, UserManager<AppUser> userManager)

        {
            _context = context;
            _reportRepository = reportRepository ?? throw new ArgumentNullException(nameof(reportRepository));
            _userManager = userManager;

        }

        // GET: ReportPosts
        public IActionResult Index()
        {
            var reportPosts = _reportRepository.GetAllReportPosts();

            var model = new ReportPostListViewModel()
            {
                TotalEntries = reportPosts.Count(),
                ReportPosts = reportPosts
                    .OrderByDescending(b => b.CreatedDate)
                    .Select(b => new ReportPostViewModel
                    {
                        Id = b.Id,
                        CreatedDate = b.CreatedDate,
                        Content = b.Content,
                        ImageUrl = b.ImageUrl,
                        Title = b.Title,
                        Location = b.Location,
                        HazardType = new HazardTypeViewModel
                        {
                            Id = b.Hazard.Id,
                            Name = b.Hazard.Name
                        },
                        ReportStatus = new ReportStatusViewModel
                        {
                            Id = b.ReportStatus.Id,
                            Name = b.ReportStatus.Name
                        },
                        Author = new AuthorViewModel
                        {
                            Id = b.UserId,
                            Name = b.User != null ? b.User.UserName : "Anonymous"
                        },
                        UpvoteCount = _reportRepository.GetUpvoteCount(b.Id),
                        LoggedInUserId = _userManager.GetUserId(User)
                    }).ToList()
            };

            return View(model);
        }



        [HttpPost]
        public IActionResult ToggleUpvote(int reportPostId)
        {
            var userId = _userManager.GetUserId(User);
            if (string.IsNullOrEmpty(userId))
                return Unauthorized();

            var upvote = _context.ReportUpvotes
                .FirstOrDefault(u => u.ReportPostId == reportPostId && u.UserId == userId);

            if (upvote != null)
            {
                _context.ReportUpvotes.Remove(upvote);
            }
            else
            {
                _context.ReportUpvotes.Add(new ReportUpvote
                {
                    ReportPostId = reportPostId,
                    UserId = userId
                });
            }

            _context.SaveChanges();
            return Redirect(Request.Headers["Referer"].ToString()); //Refreshes screen

        }




        // GET: ReportPosts/Details/5
        public IActionResult Details(int id)
        {
            var reportPost = _reportRepository.GetReportPostById(id);
            if (reportPost == null)
                return NotFound();

            var userId = _userManager.GetUserId(User);

            var model = new ReportPostViewModel()
            {
                Id = reportPost.Id,
                CreatedDate = reportPost.CreatedDate,
                ImageUrl = reportPost.ImageUrl,
                Title = reportPost.Title,
                Content = reportPost.Content,
                Location = reportPost.Location,
                HazardType = new HazardTypeViewModel()
                {
                    Id = reportPost.Hazard.Id,
                    Name = reportPost.Hazard.Name
                },
                ReportStatus = new ReportStatusViewModel()
                {
                    Id = reportPost.ReportStatus.Id,
                    Name = reportPost.ReportStatus.Name
                },
                Author = new AuthorViewModel()
                {
                    Id = reportPost.UserId,
                    Name = reportPost.User != null ? reportPost.User.UserName : "Anonymous"
                },
                UpvoteCount = _context.ReportUpvotes.Count(u => u.ReportPostId == id),
                HasUpvoted = _context.ReportUpvotes.Any(u => u.ReportPostId == id && u.UserId == userId),
                LoggedInUserId = userId
            };

            return View(model);
        }



        // GET: ReportPosts/Create
        [HttpGet]
        //[Authorize]
        public IActionResult Create()
        { 

            var hazardList = _reportRepository.GetAllHazardTypes().Select(c => new HazardTypeViewModel()
            {
                Id = c.Id,
                Name = c.Name
            }).ToList();

            var statusList = _reportRepository.GetAllReportStatuses().Select(c => new ReportStatusViewModel()
            {
                Id = c.Id,
                Name = c.Name
            }).ToList();


            //Pass the list into an EditBlogPostViewModel, which is used by the View (all other properties may be left blank, unless you want to add other default values
            var model = new EditReportPostViewModel()
            {
                HazardTypeList = hazardList,
                ReportStatusList = statusList,
                ReportStatusId = 1,

            };

            //Pass model to View
            return View(model);
        }

        [HttpPost]
        //[Authorize]
        public IActionResult Create([Bind("Title, Content, ImageToUpload, Location, HazardTypeId, ReportStatusId")] EditReportPostViewModel newReportPost)

        {

            if (newReportPost.HazardTypeId == 0)
            {
                ModelState.AddModelError("HazardTypeId", "Hazard type is required");
            }
            //if (newReportPost.ReportStatusId == 0)
            //{
            //    ModelState.AddModelError("ReportStatusId", "Status is required");
            //}

            if (ModelState.IsValid)
            {
                string fileName = "";
                if (newReportPost.ImageToUpload != null)
                {
                    //At this point you should check size, extension etc...
                    //Then persist using a new name for consistency (e.g. new Guid)
                    var extension = "." + newReportPost.ImageToUpload.FileName.Split('.')[newReportPost.ImageToUpload.FileName.Split('.').Length - 1];
                    fileName = Guid.NewGuid().ToString() + extension;
                    var path = Directory.GetCurrentDirectory() + "\\wwwroot\\images\\reportposts\\" + fileName;
                    using (var bits = new FileStream(path, FileMode.Create))
                    {
                        newReportPost.ImageToUpload.CopyTo(bits);
                    }
                }

                if (fileName.Length > 0)
                {
                    ImageUrl = "/images/reportposts/" + fileName;
                }
                else
                {
                    ImageUrl = "";
                }

                ReportPost reportPost = new ReportPost()
                {
                    Title = newReportPost.Title,
                    Content = newReportPost.Content,
                    CreatedDate = DateTime.UtcNow,
                    ImageUrl = ImageUrl,
                    //ReadCount = 0,
                    UserId = _userManager.GetUserId(User),
                    HazardTypeId = newReportPost.HazardTypeId,
                    //ReportStatusId = newReportPost.ReportStatusId,
                    ReportStatusId = 1,
                    Location = newReportPost.Location

                };

                _reportRepository.CreateReportPost(reportPost);

                return RedirectToAction("Index");
            }
            else
            {


                newReportPost.HazardTypeList = _reportRepository.GetAllHazardTypes().Select(h => new HazardTypeViewModel
                {
                    Id = h.Id,
                    Name = h.Name
                }).ToList();

                newReportPost.ReportStatusList = _reportRepository.GetAllReportStatuses().Select(s => new ReportStatusViewModel
                {
                    Id = s.Id,
                    Name = s.Name
                }).ToList();

                return View(newReportPost);
            }

        }

        public IActionResult Edit(int id)
        {
            var reportPost = _reportRepository.GetReportPostById(id);
            if (reportPost != null)
            {
                var currentUserId = _userManager.GetUserId(User);
                if (reportPost.UserId == currentUserId)
                {
                    var model = new EditReportPostViewModel
                    {
                        Id = reportPost.Id,
                        Title = reportPost.Title,
                        Content = reportPost.Content,
                        ImageUrl = reportPost.ImageUrl,
                        Location = reportPost.Location,
                        HazardTypeId = reportPost.HazardTypeId,
                        //ReportStatusId = reportPost.ReportStatusId
                        ReportStatusId = 1
                    };

Nemesys/Views/Shared/_Layout.cshtml
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager
 @{
        var currentUser = await UserManager.GetUserAsync(User);
 
 }

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nemesys</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Nemesys.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" 
    integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
    crossorigin="" />

    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
    integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
    crossorigin=""></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">  <img src="~/images/Logo.png" alt="NEMESYS Logo" style="height: 40px;" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ReportPosts" asp-action="Index">Reports</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="ReportPosts" asp-action="Create">Create Report</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HallOfFame" asp-action="Index">Hall of Fame</a>
                        </li>
                        @if (currentUser?.Role == "Investigator")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Investigation" asp-action="Index">Investigations</a>
                            </li
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Investigation" asp-action="Create">Create Investigation</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Nemesys - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>